### PR TITLE
Fix "Only variable references should be returned by reference"

### PR DESCRIPTION
**Pull request by nicolas-grekas**
As explained in #632, and easily confirmed by reading the generated code.
I suppose you'd also like a test case that actually runs this code path?
I'm not sure I'm going to be able to provide one.

/cc @greg0ire in case you'd like to provide one?

Feel free to close of course if that's not good enough.

### CODE REVIEW

**Comment by Ocramius** [comment]
> I suppose you'd also like a test case that actually runs this code path?

Yes, that's the bit that we didn't have in the current test suite, and hence why #632 went under the radar

**Comment by nicolas-grekas** [comment]
Now with tests and more fixes.

**Comment by Ocramius** [comment]
Reminder to self: retarget to `2.10.x` before merging

**Comment by nicolas-grekas** [comment]
> Reminder to self: retarget to 2.10.x before merging

done

**Comment by nicolas-grekas** [comment]
Wrong push, my bad!

**Pull request closed without merging**
