### PR TITLE
Allow PHP 8

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by greg0ire** [comment]
Blocked by https://github.com/laminas/laminas-code/issues/46 I suppose :grimacing:

**Comment by Ocramius** [comment]
Yes, and generally needs a lot of testing around PHP 8 features.

**Comment by greg0ire** [comment]
The blocker is `beberlei/assert` now, see https://github.com/beberlei/assert/pull/302

**Comment by greg0ire** [comment]
Hurdle removed: https://github.com/beberlei/assert/releases/tag/v3.3.0

**Comment by greg0ire** [comment]
Aaaaand it circles back to Doctrine: `doctrine/rst-parser` :see_no_evil: 

UPD: [fixed](https://github.com/doctrine/rst-parser/releases/tag/0.1.1)

**Comment by Ocramius** [comment]
BTW, I don't mind testing with `--ignore-platform-req=php`, but we need tests for the new features

**Comment by greg0ire** [comment]
Ah I never used that flag. Let's try it and see if tests pass at all, then we can see what tests need to be added.

**Comment by greg0ire** [comment]
> Fatal error: Uncaught Laminas\Code\Generator\Exception\InvalidArgumentException: Provided type "array|string|null" is invalid: must conform "/^[a-zA-Z_\x80-\xff][a-zA-Z0-9_\x80-\xff]*(\\[a-zA-Z_\x80-\xff][a-zA-Z0-9_\x80-\xff]*)*$/" in /home/runner/work/ProxyManager/ProxyManager/vendor/laminas/laminas-code/src/Generator/TypeGenerator.php:74

I think this needs to be updated to account for union types: https://github.com/laminas/laminas-code/blob/40919916c4ca6ad815874539cf528814429f0269/src/Generator/TypeGenerator.php#L58-L59

**Comment by Ocramius** [comment]
Yup, see https://github.com/laminas/laminas-code/pull/47#issuecomment-713582664

**Comment by martinssipenko** [comment]
Waiting on https://github.com/laminas/laminas-code/pull/57

**Comment by Lyro1** [comment]
> Waiting on [laminas/laminas-code#57](https://github.com/laminas/laminas-code/pull/57)

This PR has been merged. Any ETA?

**Comment by martinssipenko** [comment]
> > Waiting on [laminas/laminas-code#57](https://github.com/laminas/laminas-code/pull/57)
> 
> This PR has been merged. Any ETA?

It also needs to be released as part of 4.0.0, which is not done yet.

**Comment by Ocramius** [comment]
> This PR has been merged. Any ETA?

Yes: **I** merged that patch to get things moving. 😛

There is no ETA, as my priority right now is playing Cyberpunk 2077, but I am indeed working on this when my gaming rig is occupied.

**Comment by volga** [comment]
> > This PR has been merged. Any ETA?
> 
> Yes: **I** merged that patch to get things moving. 
> 
> There is no ETA, as my priority right now is playing Cyberpunk 2077, but I am indeed working on this when my gaming rig is occupied.

Is there anything I can do to help? we'd really like to upgrade to version 8 before christmas.

**Comment by Ocramius** [comment]
@Volga you can help by writing tests of codegen for proxies that require PHP 8.0.

Also need to try this patch against https://github.com/laminas/laminas-code/issues/64

I can tell you from my end that I don't expect to release for xmas, since I am closing off other client work too.

**Comment by Ocramius** [comment]
Also see https://github.com/Ocramius/ProxyManager/issues/635 for "why is PHP8 support not here yet?" :-)

**Comment by martinssipenko** [comment]
@Ocramius @Volga I tried this patch against laminas code 4.x in https://github.com/Ocramius/ProxyManager/pull/637. Does it look good? I guess after laminas-code 4.0 is released we could make the required changes in ProxyManager to fix PHPstan and other issues reported by CI.

I'd be happy to help with tests but unfortunately, I don't really get what is required.

**Comment by ghost** [comment]
@Ocramius could you just confirm that now allowing php8 isn't because ProxyManager can't run on php8 but because it cannot process php8 features, ie. if I have a codebase that only uses php7 features then ProxyManager works?

**Comment by Ocramius** [comment]
Correct, hence it cannot be allowed on PHP 8 yet.

Be aware that PHP 8 already includes type refinements in core symbols out of the box.

**Comment by ghost** [comment]
What do you mean by "Be aware that PHP 8 already includes type refinements in core symbols out of the box."? This refers to static return type + union types?

**Comment by Ocramius** [comment]
Correct: there are already such types when you switch to PHP 8 :) 

If you need to install this package with PHP 8 and you take the risks upon yourself, run with `--ignore-platform-req=php` for now, but otherwise you need to be patient and wait for integration testing to be completed.

**Comment by ghost** [comment]
If I have a php7.4 codebase and just want run it on php8 then there should be no problems with the ProxyManager?
Or are there any core PHP changes that could mess things up?

Ps: I don't mind waiting just want to confirm my understanding

**Comment by Ocramius** [comment]
In theory nothing else: in practice, it needs to be tested.

**Comment by ghost** [comment]
> ..., it needs to be tested.

Obviously. 

Thank you for taking some time to answer my questions, and good work with this package and other open source project. Your Doctrine Best practices presentation were especially impactful. Too bad I understood them only after making a mess :).

**Comment by Ocramius** [comment]
Currently picking this up for local merging and review in #658 

Indeed there were multiple PHP 8.0-related failures :-)

**Pull request closed without merging**
