### PR TITLE
Run `composer update` with `--ignore-platform-reqs` when running on `php: nightly`

### PR DESCRIPTION
**Pull request by Ocramius**

### CODE REVIEW

**Comment by malukenho** [comment]
Nikic parser?
```
Syntax error, unexpected T_STRING, expecting T_FUNCTION or T_CONST on  line 17 
```

**Comment by Ocramius** [comment]
WHOA! 
selection_153

**Comment by Ocramius** [comment]
> Syntax error, unexpected T_STRING, expecting T_FUNCTION or T_CONST on  line 17

possibly. I don't see much more in the output, sadly...

**Comment by Ocramius** [comment]
Meanwhile, shipping this: `nightly` builds!

**Pull request merged**
