### PR TITLE
Try running PHPUnit like Infection does

### PR DESCRIPTION
**Pull request by sanmai**
As per https://github.com/infection/infection/issues/762

### CODE REVIEW

**Comment by Ocramius** [comment]
@sanmai no luck? I'm also kinda clueless on what's going on...

**Comment by sanmai** [comment]
OK, let's see if PHPUnit tells us exactly where this is happening.

**Comment by sanmai** [comment]
Interestingly it now gives [a slightly different explanation for the errors](https://travis-ci.org/Ocramius/ProxyManager/builds/566804830#L638-L655). E.g. before it was:

```
1) ProxyManagerTest\GeneratorStrategy\FileWriterGeneratorStrategyTest::testGenerate
PHPUnit\Framework\Exception: Notice: stream_get_contents(): read of 8192 bytes failed with errno=9 Bad file descriptor in Standard input code on line 321
```

And now:

```
1) ProxyManagerTest\GeneratorStrategy\FileWriterGeneratorStrategyTest::testGenerate
PHPUnit\Framework\Exception: [Nothing to execute!]

Caused by
ErrorException: unserialize(): Error at offset 0 of 33 bytes in /home/travis/build/Ocramius/ProxyManager/vendor/phpunit/phpunit/src/Util/PHP/AbstractPhpProcess.php:271
```

PHP version is the same: PHP 7.4.0-dev (cli) (built: Aug  1 2019 09:31:11) ( ZTS )

**Comment by sanmai** [comment]
So far I'm unable to reproduce the issue locally with PHP 7.4.0-dev (cli) (built: Aug  1 2019 23:23:35) ( NTS )

NTS vs. ZTS might have something about it.

**Comment by sanmai** [comment]
But I was trying PHPUnit 8.2.5, and these builds are with 8.3. Starting all over.

**Comment by sanmai** [comment]
All right, now I can reproduce this issue on Docker with php:7.4-rc-cli.

**Comment by sanmai** [comment]
Since we have a reproducible case, I took liberty to report this to the upstream as https://github.com/sebastianbergmann/phpunit/issues/3772. Hope you won't mind.

**Comment by sanmai** [comment]
So you'll have to stay away from 8.3.0 while you use PHPDBG, support for it seems to be on the verge of abandonment.

**Comment by Ocramius** [comment]
Thanks for all this hard work, @sanmai!

Sad for PHPDBG - it started to become more reliable (although not much)

**Comment by sanmai** [comment]
Sounds like the claim to drop support for PHPDBG was withdraw. Thanks for the sound argument for keeping it!

**Pull request closed without merging**
