### PR TITLE
Docs - #208 document new ghost object behavior

### PR DESCRIPTION
**Pull request by Ocramius**
Provides docs for #208

### CODE REVIEW

**Comment by fntlnz** [comment]
Form is OK,  the only thing that's unclear to me is that if in the end there's any way to not skip the constructor.

**Comment by Ocramius** [comment]
@fntlnz you can actually call the constructor, if you want, but since we're setting all the state, is that an actual use-case?

**Comment by Ocramius** [comment]
@fntlnz added block to clarify that :-)

**Comment by fntlnz** [comment]
@Ocramius at the moment I don't see any use case for that. But probably because is stated "the constructor is not called" one may think  something like: "hey I have to proxy that old legacy painful object with a lot of business logic poured into the controller and I want to actually call it to be sure that the things are going as before but here's it's written that the controller isn't called. Unfortunately I can't use this tool :( ". That's quite a edge case and son of poorly designed code of course but, shit happens.
 Thanks for clarifying that :)

**Comment by Ocramius** [comment]
@fntlnz thanks for bringing it up :-)

**Pull request merged**
