### PR TITLE
README.md fix FQCN usage

### PR DESCRIPTION
**Pull request by Slamdunk**
Either the class name of first parameter or `new` instantiation is wrong

### CODE REVIEW

**Comment by Ocramius** [comment]
@Slamdunk LGTM, thanks!

**Comment by Slamdunk** [comment]
Now I can say that I found a bug in an @Ocramius project, muhahaha !

**Comment by Ocramius** [comment]
@Slamdunk didn't label it as bug

https://www.youtube.com/watch?v=y8Kyi0WNg40

**Comment by Slamdunk** [comment]
OK

I'll be back

**Pull request merged**
