### PR TITLE
Use assertDirectoryExists

### PR DESCRIPTION
**Pull request by carusogabriel**

### CODE REVIEW

**Comment by Ocramius** [comment]
Can you do a sweep for tests around file flags and see if there are similar assertions that can be used? Can be new PRs.

**Comment by carusogabriel** [comment]
Gonna search for them :mag:

**Comment by Ocramius** [comment]
Thanks!

**Comment by carusogabriel** [comment]
Nothing!

**Comment by Ocramius** [comment]
Note: failures are just on PHPStan - an upgrade of the lib will be performed before merging this :+1:

**Comment by carusogabriel** [comment]
Do you want me to PR an update to `PHPStan`?

**Comment by Ocramius** [comment]
If you want - I will personally not get to it for now.

**Comment by Ocramius** [comment]
@carusogabriel was this closed on purpose?

**Pull request closed without merging**
