### PR TITLE
[WIP] Force follow object calisthenics

### PR DESCRIPTION
**Pull request by malukenho**
Need a lot of refactors.

### CODE REVIEW

**Comment by Ocramius** [comment]
@malukenho please rebase this.

**Comment by malukenho** [comment]
@Ocramius rebased and changed `dev-master` to `1.0.0` on object calisthenics package.

**Comment by Ocramius** [comment]
@malukenho doesn't seem like there was a clean rebase yet:

not clean branch

**Comment by Ocramius** [comment]
@malukenho https://travis-ci.org/Ocramius/ProxyManager/jobs/45686016#L744

**Comment by malukenho** [comment]
Still waiting for object-calisthenics/phpcs-calisthenics-rules#16

**Comment by Ocramius** [comment]
@malukenho can you rebase this?

**Comment by Ocramius** [comment]
Checked this again: https://github.com/object-calisthenics/phpcs-calisthenics-rules is not stable enough to be used yet, and doesn't rely on PHPCS 2.0. Closing for now.

**Pull request closed without merging**
