### PR TITLE
WIP: Remove travis in favor of github workflow

### PR DESCRIPTION
**Pull request by malukenho**

### CODE REVIEW

**Comment by Ocramius** [comment]
Does infection not work with this setup?
Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by malukenho** [comment]
Yes, It works! I just moved infection to Github Actions.

Questions:

- Should we maintain the `.travis.install.sh` script?
- Can the clover coverage go away? It was not being used.
- I couldn't reproduce the `allow_failures` functionality.

**Comment by Ocramius** [comment]
I think coverage and scrutinizer-ci can both go away: we have mutation score indicators for those now :)

**Comment by Ocramius** [comment]
Should we add a build that uses `composer.lock`?

**Comment by malukenho** [comment]
You mean the simple `composer install`?

Is it good to be merged?

**Comment by Ocramius** [comment]
Yes, I think this is looking good already! :+1:

**Comment by Ocramius** [comment]
Excellent work, thank you, @malukenho! \o/

**Pull request merged**
