### PR TITLE
Support by-reference params in interceptors

### PR DESCRIPTION
**Pull request by ostrolucky**
This is needed in SncRedisBundle, see https://github.com/snc/SncRedisBundle/issues/651. We use interceptors there and currently all references are unset in proxies.

### CODE REVIEW

**Comment by Ocramius** [comment]
Unit test is fine, but we should have an integration test here 🤔

**Comment by ostrolucky** [comment]
I'm not familiar with code base, can you point me to an example testcase that you want to extend?

**Comment by nicolas-grekas** [comment]
See phpt files in tests/language-feature-scripts/ @ostrolucky

**Comment by Ocramius** [comment]
Also https://github.com/Ocramius/ProxyManager/blob/6d2458ddaf89f321ffb4a2539f17b83d761a0534/tests/ProxyManagerTest/Functional/AccessInterceptorValueHolderFunctionalTest.php

What's most useful here is having a test asset that reproduces the root issue somehow.

**Comment by ostrolucky** [comment]
added

**Review by Ocramius — APPROVED** [review]
Thanks @ostrolucky! I converted the test into a regular PHPUnit test scenario, and fixed by-ref interceptors for both access-interceptor types meanwhile :)

Will cut a release now.

**Pull request merged**
