### PR TITLE
Correct travis environment variables - adds oldest/newest deps to the matrix

### PR DESCRIPTION
**Pull request by Ocramius**

### CODE REVIEW

**Comment by Ocramius** [comment]
As the tests fail, I suppose couscous needs a bump.

**Comment by Ocramius** [comment]
Ping @mnapoli this seems to evidence some sort of dependency problem in CouscousPHP - could you check the failure, and see if it's related?

**Comment by mnapoli** [comment]
:confused: I really don't understand what the actual error is. I'll try it locally in a few minutes…

**Comment by mnapoli** [comment]
When I checkout master, run composer install and then `composer update --prefer-lowest --prefer-stable` it works :/ Could you try too maybe? Or also retry the bulid?

**Comment by Ocramius** [comment]
@mnapoli restarted

**Comment by mnapoli** [comment]
I have absolutely no idea what's happening :/ I can't reproduce locally, I have the same PHP version (I tried upgrading everything) but not the latest Composer (homebrew).

I tried downloading Composer straight from http://getcomposer.org and running exactly the same commands, but still the same result… It just works. Here is an extract:

```
  - Removing php-di/phpdoc-reader (2.0.1)
  - Installing php-di/phpdoc-reader (2.0.0)
    Loading from cache

  - Removing php-di/invoker (1.2.0)
  - Installing php-di/invoker (1.0.0)
    Loading from cache

  - Removing php-di/php-di (5.2.1)
  - Installing php-di/php-di (5.0.0)
    Loading from cache
```

Those are the only lines related to PHP-DI, Couscous isn't mentioned (you require the latest version). I don't know how to help you further.

**Comment by Ocramius** [comment]
I'll try reproducing locally. Thanks for now, @mnapoli!

**Comment by Ocramius** [comment]
I seem to be able to reproduce this locally (removed `vendor` and `composer.lock` first)

```
∙ composer update --prefer-source --prefer-lowest --prefer-stable   19:48  ocramius@Marcos-MacBook-Pro
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for couscous/couscous ^1.4.0 -> satisfiable by couscous/couscous[1.4.0].
    - couscous/couscous 1.4.0 requires php-di/php-di ~5.0 -> satisfiable by php-di/php-di[5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.0.4, 5.1.0, 5.2.0, 5.2.1].
    - Conclusion: don't install php-di/php-di 5.2.0
    - Conclusion: don't install php-di/php-di 5.1.0
    - Conclusion: don't install php-di/php-di 5.0.4
    - Conclusion: don't install php-di/php-di 5.0.3
    - Conclusion: don't install php-di/php-di 5.0.2
    - Conclusion: don't install php-di/php-di 5.0.1
    - Conclusion: don't install php-di/php-di 5.0.0
    - php-di/php-di 5.2.1 requires php-di/invoker ^1.1.1 -> satisfiable by php-di/invoker[1.1.1, 1.2.0].
    - php-di/invoker 1.1.1 requires container-interop/container-interop ~1.1 -> satisfiable by container-interop/container-interop[1.1.0].
    - php-di/invoker 1.2.0 requires container-interop/container-interop ~1.1 -> satisfiable by container-interop/container-interop[1.1.0].
    - Conclusion: don't install container-interop/container-interop 1.1.0
```

**Comment by mnapoli** [comment]
Right I just tried by removing those files and it fails indeed… It seems running composer install and then update works, for some reason.

**Comment by mnapoli** [comment]
FYI I tagged a new Couscous 1.4.1 release that requires PHP-DI `^5.2.1` (latest available). It didn't change anything, even if I require Couscous `^1.4.1` in ProxyManager:

```
  Problem 1
    - Installation request for couscous/couscous ^1.4.1 -> satisfiable by couscous/couscous[1.4.1].
    - couscous/couscous 1.4.1 requires php-di/php-di ^5.2.1 -> satisfiable by php-di/php-di[5.2.1].
    - php-di/php-di 5.2.1 requires php-di/invoker ^1.1.1 -> satisfiable by php-di/invoker[1.1.1, 1.2.0].
    - php-di/invoker 1.1.1 requires container-interop/container-interop ~1.1 -> satisfiable by container-interop/container-interop[1.1.0].
    - php-di/invoker 1.2.0 requires container-interop/container-interop ~1.1 -> satisfiable by container-interop/container-interop[1.1.0].
    - Conclusion: don't install container-interop/container-interop 1.1.0
```

I see your tried running `composer update` first, it might be the only solution (might be a Composer bug…). However it interpreted `&&` as a package name:

```
Package "&&" listed for update is not installed. Ignoring.
Package "composer" listed for update is not installed. Ignoring.
Package "update" listed for update is not installed. Ignoring.
```

**Comment by Ocramius** [comment]
> However it interpreted && as a package name:

Yeah, I was trying various things. Currently running again: seems good now.

**Comment by Ocramius** [comment]
@malukenho this can be merged. Please poke me before doing the backporting stuff.

**Comment by malukenho** [comment]
@Ocramius done

**Pull request merged**
