### PR TITLE
Just redirect right away from the "index" doc

### PR DESCRIPTION
**Pull request by malukenho**

### CODE REVIEW

**Comment by malukenho** [comment]
Btw it looks like the couscous deploy is not working.
And we should remove the HTML docs link reference form the repository description.

**Comment by Ocramius** [comment]
> Btw it looks like the couscous deploy is not working.

I'd suggest dropping couscous completely, and having custom HTML deployed to `gh-pages`

**Comment by malukenho** [comment]
@Ocramius can you change that?
Screen Shot 2019-08-28 at 12 44 57 PM

**Comment by Ocramius** [comment]
Most certainly. Just pointing it to `docs`?

**Comment by malukenho** [comment]
I think you can remove the link completely. I've created #491 with HTML redirects

**Comment by malukenho** [comment]
Linking #488

**Pull request merged**
